import { useEffect, useState } from 'react'
import { translations, type Language, type Translation } from './locales/translations'
import {
  Home, Megaphone, Plus, ClipboardList, Zap, Siren, Flag, Vote, CreditCard,
  KeyRound, LogOut, TriangleAlert, CircleCheck, Camera, ThumbsUp, LockKeyhole,
  Droplets, Flame, ArrowUp, ArrowDown, Info, ArrowUpDown
} from 'lucide-react'

type View = 'dashboard'|'news'|'report'|'requests'|'outages'|'alerts'|'complaints'|'voting'|'payments'|'owner'
type User = { flat:string; building:string; name:string; role:'resident'|'owner' }
type VoteChoice = 'yes'|'no'|'abstain'
type VoteItem = { id:number; titleKey:'vote1'|'vote2'|'vote3'; deadline:string; status:'Open'|'Closed'; yes:number; no:number; abstain:number; total:number; voted:boolean; myVote?:VoteChoice }

type RequestItem = { id:string; flat:string; descKey:'req1'|'req2'|'req3'|'req4'|'req5'|'req6'; status:'In Progress'|'Done'|'Pending'; date:string; category:'Plumbing'|'Electrical'|'Locksmith'|'Cleaning'|'Sanitation'; votes:number; photo?:boolean }

const NEWS = [
  {id:1,date:'28 Sep 2026',titleKey:'news1Title',bodyKey:'news1Body',tag:'Maintenance'},
  {id:2,date:'25 Sep 2026',titleKey:'news2Title',bodyKey:'news2Body',tag:'General'},
  {id:3,date:'20 Sep 2026',titleKey:'news3Title',bodyKey:'news3Body',tag:'Notice'},
  {id:4,date:'15 Sep 2026',titleKey:'news4Title',bodyKey:'news4Body',tag:'Community'},
] as const

const REQUESTS:RequestItem[] = [
  {id:'REQ-041',flat:'14B',descKey:'req1',status:'In Progress',date:'27 Sep 2026',photo:true,category:'Plumbing',votes:3},
  {id:'REQ-039',flat:'14B',descKey:'req2',status:'Done',date:'18 Sep 2026',photo:false,category:'Electrical',votes:7},
  {id:'REQ-035',flat:'14B',descKey:'req3',status:'Pending',date:'10 Sep 2026',photo:true,category:'Locksmith',votes:11},
  {id:'REQ-028',flat:'14B',descKey:'req4',status:'Done',date:'2 Sep 2026',photo:false,category:'Sanitation',votes:5},
]
const ALL_REQUESTS:RequestItem[] = [
  REQUESTS[0], {id:'REQ-040',flat:'7A',descKey:'req5',status:'Pending',date:'24 Sep 2026',category:'Locksmith',votes:8},
  REQUESTS[1], {id:'REQ-038',flat:'22C',descKey:'req6',status:'Pending',date:'17 Sep 2026',category:'Cleaning',votes:2}, REQUESTS[2]
]
const OUTAGES = [
  {id:1,type:'Water',start:'29 Sep 2026 09:00',end:'29 Sep 2026 14:00',floors:'All floors',reasonKey:'reason1',status:'Active'},
  {id:2,type:'Electricity',start:'5 Oct 2026 10:00',end:'5 Oct 2026 13:00',floors:'Floors 1–5',reasonKey:'reason2',status:'Upcoming'},
  {id:3,type:'Heating',start:'1 Oct 2026 00:00',end:'3 Oct 2026 00:00',floors:'All floors',reasonKey:'reason3',status:'Upcoming'},
  {id:4,type:'Elevator',start:'22 Sep 2026 08:00',end:'22 Sep 2026 17:00',floors:'Stairwell B',reasonKey:'reason4',status:'Done'},
] as const
const VOTES:VoteItem[] = [
  {id:1,titleKey:'vote1',deadline:'10 Oct 2026',status:'Open',yes:42,no:11,abstain:5,total:80,voted:false},
  {id:2,titleKey:'vote2',deadline:'15 Oct 2026',status:'Open',yes:31,no:22,abstain:8,total:80,voted:true,myVote:'yes'},
  {id:3,titleKey:'vote3',deadline:'20 Sep 2026',status:'Closed',yes:55,no:18,abstain:7,total:80,voted:true,myVote:'yes'},
]
const PAYMENTS = [
  {id:1,month:'September',amount:18500,status:'Paid',date:'5 Sep 2026',breakdown:{communal:8000,repair:4500,security:2000,cleaning:4000}},
  {id:2,month:'August',amount:18500,status:'Paid',date:'4 Aug 2026',breakdown:{communal:8000,repair:4500,security:2000,cleaning:4000}},
  {id:3,month:'July',amount:16000,status:'Paid',date:'6 Jul 2026',breakdown:{communal:8000,repair:2500,security:2000,cleaning:3500}},
  {id:4,month:'October',amount:19000,status:'Due',date:'10 Oct 2026',breakdown:{communal:8000,repair:5000,security:2000,cleaning:4000}},
] as const
const RENTED_FLATS = [
  {flat:'14B',tenant:'Asel Nurmagambetova',since:'Jan 2026',paid:true,nextDue:'Oct 2026',requests:2},
  {flat:'22A',tenant:'Dauren Bektenov',since:'Mar 2025',paid:false,nextDue:'Sep 2026',requests:0},
]

const STATUS_COLORS:Record<string,string>={Pending:'bg-amber-100 text-amber-800','In Progress':'bg-blue-100 text-blue-800',Done:'bg-emerald-100 text-emerald-800',Active:'bg-red-100 text-red-800',Upcoming:'bg-amber-100 text-amber-800',Open:'bg-blue-100 text-blue-800',Closed:'bg-gray-100 text-gray-600',Paid:'bg-emerald-100 text-emerald-800',Due:'bg-red-100 text-red-800'}
const TAG_COLORS:Record<string,string>={Maintenance:'bg-blue-50 text-blue-700',General:'bg-gray-100 text-gray-700',Notice:'bg-red-50 text-red-700',Community:'bg-green-50 text-green-700'}

function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`bg-white border border-[#D6D3A8] rounded-md ${className}`}>{children}</div>}
function SectionHeader({title,sub}:{title:string;sub?:string}){return <div className="mb-6"><h1 className="text-2xl font-bold text-[#2C4A1A] tracking-tight">{title}</h1>{sub&&<p className="text-sm text-[#697050] mt-0.5">{sub}</p>}</div>}
function Badge({raw,label}:{raw:string;label:string}){return <span className={`inline-block px-2 py-0.5 rounded text-xs font-mono font-medium ${STATUS_COLORS[raw]??'bg-gray-100 text-gray-600'}`}>{label}</span>}

const statusLabel=(t:Translation,s:string)=>s==='Pending'?t.pending:s==='In Progress'?t.inProgress:s==='Done'?t.done:s==='Active'?t.active:s==='Upcoming'?t.upcoming:s==='Open'?t.open:s==='Closed'?t.closed:s==='Paid'?t.paid:s==='Due'?t.due:s
const categoryLabel=(t:Translation,c:string)=>c==='Plumbing'?t.plumbing:c==='Electrical'?t.electrical:c==='Locksmith'?t.locksmith:c==='Cleaning'?t.cleaning:t.sanitation
const tagLabel=(t:Translation,tag:string)=>tag==='Maintenance'?t.maintenance:tag==='General'?t.general:tag==='Notice'?t.notice:t.community

function LanguageSwitcher({language,setLanguage,dark=false}:{language:Language;setLanguage:(l:Language)=>void;dark?:boolean}){
  return <div className="flex gap-1">{(['ru','kk','en'] as Language[]).map(l=><button key={l} type="button" onClick={()=>setLanguage(l)} className={`px-2.5 py-1.5 rounded text-xs font-semibold transition-colors ${language===l?(dark?'bg-white text-[#2C4A1A]':'bg-[#2C4A1A] text-white'):(dark?'bg-white/10 text-white/60 hover:bg-white/20':'bg-white text-[#697050] border border-[#D6D3A8]')}`}>{l==='kk'?'KZ':l.toUpperCase()}</button>)}</div>
}

function LoginView({onLogin,t,language,setLanguage}:{onLogin:(u:User)=>void;t:Translation;language:Language;setLanguage:(l:Language)=>void}){
  const [building,setBuilding]=useState('Navoi 47'); const [firstName,setFirstName]=useState(''); const [lastName,setLastName]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('')
  function submit(e:React.FormEvent){e.preventDefault();if(!firstName.trim()||!lastName.trim()){setError(t.nameError);return}if(password.length<4){setError(t.passwordError);return}onLogin({flat:'14B',building,name:`${firstName} ${lastName}`,role:'owner'})}
  return <div className="min-h-screen bg-[#2C4A1A] flex"><div className="hidden lg:flex flex-col justify-between w-[420px] p-12 border-r border-white/10"><div><div className="text-white/60 text-xs font-mono tracking-widest uppercase mb-12">{t.appName}</div><h1 className="text-white text-5xl font-bold leading-tight mb-4">{t.heroTitle}</h1><p className="text-white/60 text-base leading-relaxed">{t.heroText}</p></div><div className="text-white/30 text-xs font-mono">{t.location}</div></div><div className="flex-1 flex items-center justify-center p-6 sm:p-8 bg-[#F6F5DC]"><div className="w-full max-w-sm"><div className="flex items-center justify-between mb-8"><div className="text-[#697050] text-xs font-mono tracking-widest uppercase lg:hidden">{t.appName}</div><LanguageSwitcher language={language} setLanguage={setLanguage}/></div><h2 className="text-[#1E2A0E] text-2xl font-bold mb-1">{t.login}</h2><p className="text-[#697050] text-sm mb-8">{t.loginSubtitle}</p><form onSubmit={submit} className="space-y-4"><label className="block text-xs text-[#697050]">{t.complex}<select className="mt-1.5 w-full bg-white border border-[#D6D3A8] rounded-md px-3 py-2.5 text-sm" value={building} onChange={e=>setBuilding(e.target.value)}><option>Navoi 47</option><option>Abai 12</option><option>Almagul 5</option></select></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-xs text-[#697050]">{t.firstName}<input className="mt-1.5 w-full bg-white border border-[#D6D3A8] rounded-md px-3 py-2.5 text-sm" value={firstName} onChange={e=>setFirstName(e.target.value)}/></label><label className="text-xs text-[#697050]">{t.lastName}<input className="mt-1.5 w-full bg-white border border-[#D6D3A8] rounded-md px-3 py-2.5 text-sm" value={lastName} onChange={e=>setLastName(e.target.value)}/></label></div><label className="block text-xs text-[#697050]">{t.password}<input type="password" placeholder={t.passwordPlaceholder} className="mt-1.5 w-full bg-white border border-[#D6D3A8] rounded-md px-3 py-2.5 text-sm" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="text-red-600 text-xs">{error}</p>}<button className="w-full bg-[#2C4A1A] hover:bg-[#3A6022] text-white font-semibold rounded-md py-2.5 text-sm">{t.signIn}</button></form><p className="text-[#697050] text-xs text-center mt-6">{t.noAccess}</p></div></div></div>
}

type NavKey='dashboard'|'news'|'report'|'requests'|'outages'|'alerts'|'complaints'|'voting'|'payments'|'owner'
const NAV_ITEMS:{view:View;labelKey:NavKey;icon:React.ElementType;badge?:number}[]=[
  {view:'dashboard',labelKey:'dashboard',icon:Home},{view:'news',labelKey:'news',icon:Megaphone},{view:'report',labelKey:'report',icon:Plus},{view:'requests',labelKey:'requests',icon:ClipboardList,badge:2},{view:'outages',labelKey:'outages',icon:Zap,badge:1},{view:'alerts',labelKey:'alerts',icon:Siren},{view:'complaints',labelKey:'complaints',icon:Flag},{view:'voting',labelKey:'voting',icon:Vote,badge:1},{view:'payments',labelKey:'payments',icon:CreditCard},{view:'owner',labelKey:'owner',icon:KeyRound}
]
function Sidebar({current,onNav,user,onLogout,language,setLanguage,t}:{current:View;onNav:(v:View)=>void;user:User;onLogout:()=>void;language:Language;setLanguage:(l:Language)=>void;t:Translation}){return <aside className="hidden md:flex w-56 shrink-0 bg-[#2C4A1A] flex-col min-h-screen"><div className="px-4 py-5 border-b border-white/10"><div className="text-white font-bold">{user.building}</div><div className="text-white/50 text-xs font-mono mt-0.5">{t.flatShort} {user.flat} · {user.name}</div></div><nav className="flex-1 py-3 space-y-0.5 px-2">{NAV_ITEMS.map(item=><button key={item.view} onClick={()=>onNav(item.view)} className={`w-full text-left flex items-center gap-2.5 px-3 py-2 rounded text-sm ${current===item.view?'bg-white/15 text-white font-medium':'text-white/60 hover:text-white hover:bg-white/10'}`}><item.icon size={18}/><span className="flex-1">{t[item.labelKey]}</span>{item.badge&&<span className="bg-[#A07C12] text-white text-[10px] font-bold rounded-full w-4 h-4 flex items-center justify-center">{item.badge}</span>}</button>)}</nav><div className="px-4 py-4 border-t border-white/10"><LanguageSwitcher language={language} setLanguage={setLanguage} dark/><button onClick={onLogout} className="flex items-center gap-2 text-white/50 text-xs hover:text-white mt-4"><LogOut size={15}/>{t.logout}</button></div></aside>}

function DashboardView({onNav,t}:{onNav:(v:View)=>void;t:Translation}){const openReq=REQUESTS.filter(r=>r.status!=='Done');return <div><div className="bg-[#A07C12] text-white px-5 py-3 flex items-center gap-3 -mx-4 sm:-mx-6 -mt-4 sm:-mt-6 mb-6"><Siren size={20}/><div className="flex-1"><b className="text-sm">{t.emergencyNotification}: </b><span className="text-sm text-white/90">{t.emergencyWaterText}</span></div><button onClick={()=>onNav('alerts')} className="text-xs underline">{t.moreDetails}</button></div><SectionHeader title={t.homeTitle} sub={`${userBuilding()} · ${t.apartment} 14B`}/><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{[{l:t.myRequests,v:'2',s:t.activeCount,a:'requests'},{l:t.nextPayment,v:'19 000 ₸',s:t.paymentUntil,a:'payments'},{l:t.openVotes,v:'1',s:t.waitingForVote,a:'voting'},{l:t.outagesCount,v:'3',s:t.scheduled,a:'outages'}].map(x=><button key={x.l} onClick={()=>onNav(x.a as View)} className="bg-white border border-[#D6D3A8] rounded-md p-4 text-left hover:border-[#2C4A1A]"><div className="text-xl font-bold text-[#2C4A1A]">{x.v}</div><div className="text-xs text-[#697050] mt-0.5">{x.l}</div><div className="text-[10px] text-[#697050] font-mono mt-1">{x.s}</div></button>)}</div><div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2"><div className="flex justify-between mb-3"><h2 className="font-semibold text-[#2C4A1A]">{t.latestNews}</h2><button onClick={()=>onNav('news')} className="text-xs text-[#A07C12]">{t.all} →</button></div><Card>{NEWS.slice(0,3).map((n,i)=><div key={n.id} className={`px-4 py-3 ${i<2?'border-b border-[#F6F5DC]':''}`}><div className="flex items-start gap-3"><span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${TAG_COLORS[n.tag]}`}>{tagLabel(t,n.tag)}</span><div><div className="font-medium text-sm text-[#1E2A0E]">{t[n.titleKey]}</div><div className="text-xs text-[#697050]">{n.date}</div></div></div></div>)}</Card></div><div><div className="flex justify-between mb-3"><h2 className="font-semibold text-[#2C4A1A]">{t.myRequests}</h2><button onClick={()=>onNav('requests')} className="text-xs text-[#A07C12]">{t.all} →</button></div><Card>{openReq.map((r,i)=><div key={r.id} className={`px-4 py-3 ${i<openReq.length-1?'border-b border-[#F6F5DC]':''}`}><div className="flex justify-between"><span className="font-mono text-[11px] text-[#697050]">{r.id}</span><Badge raw={r.status} label={statusLabel(t,r.status)}/></div><div className="text-sm text-[#1E2A0E] mt-1">{t[r.descKey]}</div><div className="text-[11px] text-[#697050] font-mono mt-1">{r.date} · {categoryLabel(t,r.category)}</div></div>)}</Card><button onClick={()=>onNav('report')} className="w-full mt-3 bg-[#A07C12] text-white font-semibold rounded-md py-2 text-sm flex items-center justify-center gap-1"><Plus size={16}/>{t.newRequest}</button></div></div></div>}
function userBuilding(){return 'Navoi 47'}

function NewsView({t}:{t:Translation}){const [filter,setFilter]=useState('All');const tags=['All','Maintenance','General','Notice','Community'];const filtered=filter==='All'?NEWS:NEWS.filter(n=>n.tag===filter);return <div><SectionHeader title={t.newsTitle} sub={t.newsSubtitle}/><div className="flex gap-2 mb-5 flex-wrap">{tags.map(tag=><button key={tag} onClick={()=>setFilter(tag)} className={`px-3 py-1 rounded text-xs border ${filter===tag?'bg-[#2C4A1A] text-white':'bg-white text-[#2C4A1A]'}`}>{tag==='All'?t.allFilter:tagLabel(t,tag)}</button>)}</div><div className="space-y-3">{filtered.map(n=><Card key={n.id} className="p-5"><div className="flex items-center gap-2 mb-2"><span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${TAG_COLORS[n.tag]}`}>{tagLabel(t,n.tag)}</span><span className="text-xs text-[#697050] font-mono">{n.date}</span></div><h3 className="font-semibold text-[#2C4A1A]">{t[n.titleKey]}</h3><p className="text-sm text-[#697050] mt-1">{t[n.bodyKey]}</p></Card>)}</div></div>}

function ReportView({t}:{t:Translation}){const [form,setForm]=useState({category:'',desc:'',location:'',photo:false});const [submitted,setSubmitted]=useState(false);const similar=form.desc.toLowerCase().includes('lock')||form.desc.toLowerCase().includes('замок')||form.desc.toLowerCase().includes('лифт');if(submitted)return <div><SectionHeader title={t.requestSubmitted}/><Card className="p-8 text-center max-w-md mx-auto"><CircleCheck size={42} className="mx-auto mb-4 text-[#2C4A1A]"/><h2 className="font-bold text-[#2C4A1A]">{t.requestRegistered}</h2><p className="text-sm text-[#697050] my-3">{t.requestRegisteredText}</p><button onClick={()=>setSubmitted(false)} className="bg-[#2C4A1A] text-white px-5 py-2 rounded text-sm">{t.submitAnother}</button></Card></div>;return <div><SectionHeader title={t.requestTitle} sub={t.requestSubtitle}/><Card className="p-5 space-y-4 max-w-lg"><label className="block text-xs text-[#697050]">{t.category}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-1.5 w-full border border-[#D6D3A8] rounded px-3 py-2 text-sm"><option value="">{t.chooseCategory}</option>{[t.plumbing,t.electrical,t.elevator,t.locksmith,t.cleaning,t.heating,t.roofing,t.other].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-xs text-[#697050]">{t.place}<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder={t.placePlaceholder} className="mt-1.5 w-full border border-[#D6D3A8] rounded px-3 py-2 text-sm"/></label><label className="block text-xs text-[#697050]">{t.description}<textarea value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} placeholder={t.descriptionPlaceholder} className="mt-1.5 w-full border border-[#D6D3A8] rounded px-3 py-2 text-sm resize-none h-24"/></label>{similar&&<div className="bg-amber-50 border border-amber-200 rounded p-3"><div className="flex gap-2 text-xs font-semibold text-amber-800"><TriangleAlert size={15}/>{t.similarRequest}</div><p className="text-xs text-amber-700 mt-1">{t.similarText}</p><button className="mt-2 text-xs bg-amber-200 px-3 py-1 rounded">{t.joinRecommended}</button></div>}<div><div className="text-xs text-[#697050] mb-1.5">{t.photoOptional}</div><button type="button" onClick={()=>setForm({...form,photo:!form.photo})} className="w-full border-2 border-dashed border-[#D6D3A8] rounded-md p-5 text-sm text-[#697050] flex items-center justify-center gap-2">{form.photo?<><CircleCheck size={16}/>{t.photoAttached}</>:<><Camera size={16}/>{t.attachPhoto}</>}</button></div><button onClick={()=>form.category&&form.desc&&setSubmitted(true)} className="w-full bg-[#A07C12] text-white font-semibold rounded py-2.5 text-sm">{t.sendRequest}</button></Card></div>}

function RequestsView({t}:{t:Translation}){const [tab,setTab]=useState<'mine'|'all'>('mine');const list=tab==='mine'?REQUESTS:ALL_REQUESTS;return <div><SectionHeader title={t.requestsTitle} sub={t.requestsSubtitle}/><div className="flex gap-1 mb-5 bg-white border border-[#D6D3A8] rounded-md p-1 w-fit"><button onClick={()=>setTab('mine')} className={`px-4 py-1.5 rounded text-sm ${tab==='mine'?'bg-[#2C4A1A] text-white':''}`}>{t.mine}</button><button onClick={()=>setTab('all')} className={`px-4 py-1.5 rounded text-sm ${tab==='all'?'bg-[#2C4A1A] text-white':''}`}>{t.allBuilding}</button></div><div className="space-y-3">{list.map(r=><Card key={r.id} className="p-4"><div className="flex items-start gap-4"><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><span className="font-mono text-[11px] text-[#697050]">{r.id}</span><Badge raw={r.status} label={statusLabel(t,r.status)}/><span className="text-[11px] text-[#697050]">{categoryLabel(t,r.category)}</span>{r.photo===true&&<Camera size={14}/>}</div><p className="text-sm font-medium text-[#1E2A0E] mt-1">{t[r.descKey]}</p><div className="flex gap-3 mt-1 text-[11px] text-[#697050]"><span>{r.date}</span><span>{t.flatShort} {r.flat}</span><span className="flex gap-1"><ThumbsUp size={13}/>{r.votes} {t.supported}</span></div></div>{tab==='all'&&<button className="text-xs text-[#A07C12]">{t.join}</button>}</div>{r.status==='In Progress'&&<div className="mt-3 pt-3 border-t border-[#F6F5DC] flex gap-3 text-[10px] text-[#697050]"><span>1. {t.accepted}</span><span>2. {t.inProgress}</span><span>3. {t.done}</span></div>}</Card>)}</div></div>}

function OutagesView({t}:{t:Translation}){const icons:Record<string,React.ElementType>={Water:Droplets,Electricity:Zap,Heating:Flame,Elevator:ArrowUpDown};const type=(x:string)=>x==='Water'?t.water:x==='Electricity'?t.electricity:x==='Heating'?t.heating:t.elevator;const floors=(x:string)=>x==='All floors'?t.allFloors:x==='Floors 1–5'?t.floors15:t.stairwellB;return <div><SectionHeader title={t.outagesTitle} sub={t.outagesSubtitle}/><div className="space-y-3">{OUTAGES.map(o=>{const Icon=icons[o.type];return <Card key={o.id} className={`p-4 ${o.status==='Active'?'border-red-200 bg-red-50':''}`}><div className="flex items-start gap-3"><Icon size={27} className="text-[#2C4A1A] shrink-0"/><div className="flex-1"><div className="flex items-center gap-2"><b className="text-sm">{type(o.type)}</b><Badge raw={o.status} label={statusLabel(t,o.status)}/></div><p className="text-xs text-[#697050] my-1">{t[o.reasonKey]}</p><div className="flex flex-wrap gap-4 text-[11px] font-mono text-[#697050]"><span>{t.from} {o.start}</span><span>{t.to} {o.end}</span><span>{t.zone} {floors(o.floors)}</span></div></div></div></Card>})}</div></div>}

function AlertsView({t}:{t:Translation}){const alerts=[{id:1,time:'29 Sep 2026 08:45',title:t.alert1Title,body:t.alert1Body,level:'warning'},{id:2,time:'15 Sep 2026 19:10',title:t.alert2Title,body:t.alert2Body,level:'danger'},{id:3,time:'1 Sep 2026 07:00',title:t.alert3Title,body:t.alert3Body,level:'info'}];const colors:Record<string,string>={warning:'border-amber-300 bg-amber-50',danger:'border-red-300 bg-red-50',info:'border-blue-200 bg-blue-50'};const icons:Record<string,React.ElementType>={warning:TriangleAlert,danger:Siren,info:Info};return <div><SectionHeader title={t.alertsTitle} sub={t.alertsSubtitle}/><div className="space-y-3">{alerts.map(a=>{const Icon=icons[a.level];return <div key={a.id} className={`border rounded-md p-4 ${colors[a.level]}`}><div className="flex gap-3"><Icon size={22} className="text-[#2C4A1A] shrink-0"/><div><div className="flex gap-2 flex-wrap"><b className="text-sm">{a.title}</b><span className="text-[10px] font-mono text-[#697050]">{a.time}</span></div><p className="text-sm text-[#697050] mt-1">{a.body}</p></div></div></div>})}</div></div>}

function ComplaintsView({t}:{t:Translation}){const [show,setShow]=useState(false);const [submitted,setSubmitted]=useState(false);const complaints=[{id:1,from:'12A',about:'13A',subject:t.complaint1,status:'Under review',date:'26 Sep 2026'},{id:2,from:'8C',about:'8B',subject:t.complaint2,status:'Resolved',date:'19 Sep 2026'},{id:3,from:'3B',about:t.commonArea,subject:t.complaint3,status:'Closed',date:'12 Sep 2026'}];const cstatus=(s:string)=>s==='Under review'?t.underReview:s==='Resolved'?t.resolved:t.closed;return <div><SectionHeader title={t.complaintsTitle} sub={t.complaintsSubtitle}/><button onClick={()=>setShow(!show)} className="bg-[#A07C12] text-white text-sm font-semibold px-4 py-2 rounded flex gap-1"><Plus size={16}/>{t.fileComplaint}</button>{show&&!submitted&&<Card className="p-5 my-5 max-w-lg"><h3 className="font-semibold text-[#2C4A1A] mb-4">{t.newComplaint}</h3><div className="space-y-3"><label className="block text-xs text-[#697050]">{t.aboutFlat}<input className="mt-1 w-full border border-[#D6D3A8] rounded px-3 py-2"/></label><label className="block text-xs text-[#697050]">{t.subject}<input placeholder={t.subjectPlaceholder} className="mt-1 w-full border border-[#D6D3A8] rounded px-3 py-2"/></label><label className="block text-xs text-[#697050]">{t.details}<textarea className="mt-1 w-full border border-[#D6D3A8] rounded px-3 py-2 h-20"/></label><p className="flex gap-1.5 text-[11px] text-[#697050]"><LockKeyhole size={13}/>{t.anonymousInfo}</p><button onClick={()=>setSubmitted(true)} className="w-full bg-[#2C4A1A] text-white text-sm font-semibold py-2 rounded">{t.send}</button></div></Card>}{submitted&&<div className="flex gap-2 bg-emerald-50 border border-emerald-200 rounded-md p-4 my-5 text-sm text-emerald-800"><CircleCheck size={18}/>{t.complaintAccepted}</div>}<h3 className="font-semibold text-[#2C4A1A] my-3 text-sm">{t.history}</h3><div className="space-y-2">{complaints.map(c=><Card key={c.id} className="p-4"><div className="flex gap-2"><Badge raw={c.status} label={cstatus(c.status)}/><span className="text-[11px] text-[#697050]">{c.date}</span></div><p className="text-sm font-medium mt-1">{c.subject}</p><p className="text-xs text-[#697050]">{t.flatShort} {c.from} → {c.about}</p></Card>)}</div></div>}

function VotingView({t}:{t:Translation}){const [votes,setVotes]=useState<VoteItem[]>(()=>{const saved=localStorage.getItem('votes');return saved?JSON.parse(saved) as VoteItem[]:VOTES});useEffect(()=>localStorage.setItem('votes',JSON.stringify(votes)),[votes]);function vote(id:number,choice:VoteChoice){setVotes(vs=>vs.map(v=>v.id===id?{...v,voted:true,myVote:choice,[choice]:v[choice]+1}:v))}return <div><SectionHeader title={t.votingTitle} sub={t.votingSubtitle}/><div className="space-y-4">{votes.map(v=>{const pct=(n:number)=>Math.round(n/v.total*100);return <Card key={v.id} className="p-5"><div className="flex gap-2 mb-1"><Badge raw={v.status} label={statusLabel(t,v.status)}/><span className="text-[11px] text-[#697050]">{t.until} {v.deadline}</span></div><h3 className="font-semibold text-[#2C4A1A] mb-4">{t[v.titleKey]}</h3>{([['yes',t.yes,v.yes,'bg-emerald-500'],['no',t.no,v.no,'bg-red-400'],['abstain',t.abstain,v.abstain,'bg-gray-300']] as const).map(([key,label,n,color])=><div key={key} className="flex items-center gap-3 mb-2"><span className="text-xs text-[#697050] w-24">{label}</span><div className="flex-1 bg-[#F6F5DC] rounded-full h-2"><div className={`h-2 rounded-full ${color}`} style={{width:`${pct(n)}%`}}/></div><span className="text-xs font-mono text-[#697050] w-16 text-right">{n} ({pct(n)}%)</span></div>)}<div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mt-4"><span className="text-[11px] text-[#697050]">{t.voted}: {v.yes+v.no+v.abstain} {t.of} {v.total}</span>{v.status==='Open'&&!v.voted&&<div className="flex gap-2">{(['yes','no','abstain'] as VoteChoice[]).map(c=><button key={c} onClick={()=>vote(v.id,c)} className="px-3 py-1.5 rounded text-xs border">{c==='yes'?t.yes:c==='no'?t.no:t.abstainAction}</button>)}</div>}{v.voted&&<span className="flex items-center gap-1 text-xs text-emerald-700"><CircleCheck size={14}/>{t.youVoted}: {v.myVote==='yes'?t.yes:v.myVote==='no'?t.no:t.abstain}</span>}</div></Card>})}</div></div>}

function PaymentsView({t}:{t:Translation}){const [expanded,setExpanded]=useState<number|null>(4);const month=(m:string)=>m==='September'?t.september:m==='August'?t.august:m==='July'?t.july:t.october;return <div><SectionHeader title={t.paymentsTitle} sub={`${t.paymentsSubtitle} · ${t.apartment} 14B`}/><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">{[{l:t.toPay,v:'19 000 ₸',s:t.october},{l:t.paid2026,v:'214 500 ₸',s:t.nineMonths},{l:t.debt,v:'0 ₸',s:t.noOverdue}].map(x=><Card key={x.l} className="p-4"><div className="text-xl font-bold text-[#2C4A1A]">{x.v}</div><div className="text-xs text-[#697050]">{x.l}</div><div className="text-[10px] text-[#697050]">{x.s}</div></Card>)}</div><div className="space-y-2">{PAYMENTS.map(p=><Card key={p.id}><button onClick={()=>setExpanded(expanded===p.id?null:p.id)} className="w-full px-4 py-3 flex items-center gap-3 text-left"><Badge raw={p.status} label={statusLabel(t,p.status)}/><span className="flex-1 text-sm font-medium">{month(p.month)}</span><span className="font-mono text-sm font-semibold">{p.amount.toLocaleString()} ₸</span><span className="hidden sm:inline text-xs text-[#697050]">{p.date}</span>{expanded===p.id?<ArrowUp size={14}/>:<ArrowDown size={14}/>}</button>{expanded===p.id&&<div className="px-4 pb-4 border-t border-[#F6F5DC] pt-3">{Object.entries(p.breakdown).map(([k,v])=><div key={k} className="flex justify-between text-sm mb-1"><span className="text-[#697050]">{k==='communal'?t.communal:k==='repair'?t.repairFund:k==='security'?t.security:t.cleaning}</span><span className="font-mono">{v.toLocaleString()} ₸</span></div>)}<div className="flex justify-between text-sm font-semibold pt-2 border-t"><span>{t.total}</span><span>{p.amount.toLocaleString()} ₸</span></div>{p.status==='Due'&&<button className="mt-4 w-full bg-[#A07C12] text-white font-semibold py-2.5 rounded text-sm">{t.payOnline}</button>}</div>}</Card>)}</div></div>}

function OwnerView({t}:{t:Translation}){return <div><SectionHeader title={t.ownerTitle} sub={t.ownerSubtitle}/><div className="space-y-4">{RENTED_FLATS.map(f=><Card key={f.flat} className={`p-5 ${!f.paid?'border-red-200':''}`}><div className="flex justify-between"><div><div className="text-lg font-bold text-[#2C4A1A]">{t.flatShort} {f.flat}</div><div className="text-sm text-[#697050]">{t.tenant}: {f.tenant}</div><div className="text-xs text-[#697050]">{t.since} {f.since}</div></div><Badge raw={f.paid?'Paid':'Due'} label={f.paid?t.paid:t.due}/></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-3 mt-3 border-t"><div><div className="text-xs text-[#697050]">{t.nextPaymentLabel}</div><b className="text-sm">{f.nextDue}</b></div><div><div className="text-xs text-[#697050]">{t.activeRequests}</div><b className="text-sm">{f.requests}</b></div><div><div className="text-xs text-[#697050]">{t.status}</div><div className={`flex items-center gap-1 text-sm font-semibold ${f.paid?'text-emerald-700':'text-red-700'}`}>{f.paid?<CircleCheck size={15}/>:<TriangleAlert size={15}/>} {f.paid?t.noDebt:t.overdue}</div></div></div>{!f.paid&&<div className="mt-3 pt-3 border-t border-red-100"><p className="text-xs text-red-700">{t.paymentMissing}</p><button className="mt-2 text-xs bg-red-100 text-red-800 px-3 py-1.5 rounded">{t.sendReminder}</button></div>}</Card>)}</div></div>}

export default function App(){
  const [user,setUser]=useState<User|null>(()=>{const x=localStorage.getItem('user');return x?JSON.parse(x) as User:null})
  const [view,setView]=useState<View>(()=>(localStorage.getItem('view') as View)||'dashboard')
  const [language,setLanguage]=useState<Language>(()=>(localStorage.getItem('language') as Language)||'ru')
  useEffect(()=>{user?localStorage.setItem('user',JSON.stringify(user)):localStorage.removeItem('user')},[user])
  useEffect(()=>localStorage.setItem('view',view),[view]);useEffect(()=>localStorage.setItem('language',language),[language])
  const t=translations[language]
  if(!user)return <LoginView onLogin={u=>{setUser(u);setView('dashboard')}} t={t} language={language} setLanguage={setLanguage}/>
  const views:Record<View,React.ReactNode>={dashboard:<DashboardView onNav={setView} t={t}/>,news:<NewsView t={t}/>,report:<ReportView t={t}/>,requests:<RequestsView t={t}/>,outages:<OutagesView t={t}/>,alerts:<AlertsView t={t}/>,complaints:<ComplaintsView t={t}/>,voting:<VotingView t={t}/>,payments:<PaymentsView t={t}/>,owner:<OwnerView t={t}/>}
  return <div className="min-h-screen bg-[#F6F5DC]"><div className="flex min-h-screen"><Sidebar current={view} onNav={setView} user={user} onLogout={()=>{setUser(null);setView('dashboard')}} language={language} setLanguage={setLanguage} t={t}/><div className="flex-1 min-w-0"><div className="md:hidden bg-[#2C4A1A] text-white px-4 py-3 flex items-center gap-2"><span className="font-semibold flex-1 truncate">{user.building}</span><LanguageSwitcher language={language} setLanguage={setLanguage} dark/><select value={view} onChange={e=>setView(e.target.value as View)} className="bg-white text-[#2C4A1A] rounded px-2 py-1 text-sm max-w-[130px]">{NAV_ITEMS.map(item=><option key={item.view} value={item.view}>{t[item.labelKey]}</option>)}</select></div><main className="p-4 sm:p-6 overflow-auto max-w-5xl">{views[view]}</main></div></div></div>
}
