export type Language = 'ru' | 'kk' | 'en'

export const translations = {
  ru: {
    dashboard:'Главная', news:'Новости', report:'Подать заявку', requests:'Мои заявки', outages:'Отключения', alerts:'Экстренные', complaints:'Жалобы', voting:'Голосования', payments:'Платежи', owner:'Мои объекты', logout:'Выйти',
    appName:'ЖК Управление', heroTitle:'Ваш дом. Ваш голос.', heroText:'Единый портал для жильцов жилого комплекса — заявки, новости, голосования и платежи в одном месте.', location:'Алматы · Казахстан · 2026', login:'Вход в систему', loginSubtitle:'Войдите в личный кабинет жильца', complex:'Жилой комплекс', firstName:'Имя', lastName:'Фамилия', password:'Пароль', passwordPlaceholder:'Введите пароль', signIn:'Войти', noAccess:'Нет доступа? Обратитесь к управляющему комплекса.', nameError:'Введите имя и фамилию', passwordError:'Пароль должен содержать минимум 4 символа', flatShort:'Кв.', apartment:'Квартира',
    emergencyNotification:'Экстренное уведомление', emergencyWaterText:'Отключение воды сегодня с 09:00 до 14:00 — плановые работы.', moreDetails:'Подробнее', homeTitle:'Главная', myRequests:'Мои заявки', activeCount:'активных', nextPayment:'Следующий платёж', paymentUntil:'до 10 окт', openVotes:'Открытых голосований', waitingForVote:'ждут вашего голоса', outagesCount:'Отключений', scheduled:'запланировано', latestNews:'Последние новости', all:'Все', newRequest:'Новая заявка',
    maintenance:'Обслуживание', general:'Общее', notice:'Уведомление', community:'Сообщество', newsTitle:'Новости дома', newsSubtitle:'Официальный канал управляющей компании', allFilter:'Все',
    news1Title:'Техническое обслуживание лифта завершено', news1Body:'Оба лифта в подъезде А прошли обслуживание и работают в штатном режиме.', news2Title:'Подписан новый договор с управляющей компанией', news2Body:'С 1 октября Almaty Comfort LLC будет управлять коммунальными услугами и начислениями.', news3Title:'Напоминание о правилах парковки', news3Body:'Автомобили, блокирующие аварийный выезд, будут эвакуированы согласно правилам дома.', news4Title:'Осенняя уборка в субботу', news4Body:'5 октября состоится добровольная уборка двора. Перчатки и пакеты предоставляются. Начало в 10:00.',
    requestTitle:'Подать заявку', requestSubtitle:'Сообщите о неисправности или проблеме в доме', category:'Категория', chooseCategory:'Выберите категорию…', plumbing:'Сантехника', electrical:'Электрика', elevator:'Лифт', locksmith:'Замок / Дверь', cleaning:'Уборка', heating:'Отопление', roofing:'Кровля', other:'Другое', place:'Место', placePlaceholder:'Напр. Подъезд Б, 3 этаж', description:'Описание', descriptionPlaceholder:'Опишите проблему подробно…', similarRequest:'Похожая заявка уже существует', similarText:'REQ-035: «Замок входной двери сломан» (11 голосов). Присоединиться к этой заявке?', joinRecommended:'Присоединиться (рекомендуется)', photoOptional:'Фото (необязательно)', photoAttached:'photo_20260929.jpg прикреплено', attachPhoto:'Нажмите чтобы прикрепить фото', sendRequest:'Отправить заявку', requestSubmitted:'Заявка подана', requestRegistered:'Заявка REQ-042 зарегистрирована', requestRegisteredText:'Управляющий получил уведомление. Ожидайте обратной связи в течение 24 часов.', submitAnother:'Подать ещё одну',
    requestsTitle:'Заявки', requestsSubtitle:'История и статус ваших обращений', mine:'Мои заявки', allBuilding:'Все заявки дома', join:'Присоединиться', supported:'поддержали', accepted:'Принято', inProgress:'В работе', done:'Выполнено', pending:'Ожидает',
    req1:'Протечка трубы горячей воды под кухонной раковиной', req2:'Мигает свет в коридоре на 4 этаже', req3:'Сломан замок входной двери — ключ застревает', req4:'Засорен мусоропровод на 3 этаже', req5:'Сломана защёлка окна в подъезде на 6 этаже', req6:'Граффити на стене подвала возле парковки', sanitation:'Санитария',
    outagesTitle:'Плановые отключения', outagesSubtitle:'Запланированные работы и перебои в обслуживании', water:'Вода', electricity:'Электричество', active:'Активно', upcoming:'Предстоящее', allFloors:'Все этажи', floors15:'Этажи 1–5', stairwellB:'Подъезд Б', from:'С:', to:'До:', zone:'Зона:', reason1:'Плановая проверка труб и давления', reason2:'Обновление электрощита в подвале', reason3:'Промывка системы отопления перед началом сезона', reason4:'Ежегодная проверка безопасности',
    alertsTitle:'Экстренные уведомления', alertsSubtitle:'Важные сообщения от управления и аварийных служб', alert1Title:'Отключение воды', alert1Body:'Горячая и холодная вода отключены до 14:00. Причина: плановая проверка давления в трубах.', alert2Title:'Задымление в подвале', alert2Body:'Пожарная служба выезжала на ложное срабатывание датчика в подвале. Угрозы нет.', alert3Title:'Отопительный сезон', alert3Body:'С 1 октября начинается отопительный сезон. Ожидается запуск систем в срок.',
    complaintsTitle:'Жалобы на соседей', complaintsSubtitle:'Анонимное обращение к управляющему', fileComplaint:'Подать жалобу', newComplaint:'Новая жалоба', aboutFlat:'На кого (квартира)', subject:'Тема', subjectPlaceholder:'Шум, запах, мусор…', details:'Подробности', anonymousInfo:'Ваша жалоба будет анонимной. Управляющий свяжется с обеими сторонами.', send:'Отправить', complaintAccepted:'Жалоба принята анонимно. Управляющий рассмотрит её в течение 48 часов.', history:'История обращений', underReview:'На рассмотрении', resolved:'Решено', closed:'Закрыто', complaint1:'Шум после 23:00', complaint2:'Сигаретный дым в общем коридоре', complaint3:'Собака без поводка в лифте', commonArea:'Общая зона',
    votingTitle:'Голосования', votingSubtitle:'Решения принимаются большинством голосов собственников', open:'Открыто', yes:'За', no:'Против', abstain:'Воздержались', abstainAction:'Воздержаться', voted:'Проголосовало', of:'из', youVoted:'Вы проголосовали', vote1:'Установить камеры видеонаблюдения во всех подъездах', vote2:'Увеличить уборку общих зон до 3 раз в неделю', vote3:'Покрасить фасад дома — утвердить статью бюджета 2026', until:'до',
    paymentsTitle:'Платежи', paymentsSubtitle:'Коммунальные взносы', toPay:'К оплате', october:'Октябрь 2026', paid2026:'Оплачено в 2026', nineMonths:'9 месяцев', debt:'Задолженность', noOverdue:'Нет просроченных', paid:'Оплачено', due:'К оплате', september:'Сентябрь 2026', august:'Август 2026', july:'Июль 2026', communal:'Коммунальные', repairFund:'Ремонтный фонд', security:'Охрана', total:'Итого', payOnline:'Оплатить онлайн',
    ownerTitle:'Мои объекты', ownerSubtitle:'Управление арендованными квартирами', tenant:'Арендатор', since:'С', nextPaymentLabel:'Следующий платёж', activeRequests:'Активных заявок', status:'Статус', noDebt:'Нет задолженности', overdue:'Просрочен', paymentMissing:'Платёж не получен. Уведомление отправлено арендатору.', sendReminder:'Отправить напоминание'
  },
  kk: {
    dashboard:'Басты бет', news:'Жаңалықтар', report:'Өтінім беру', requests:'Менің өтінімдерім', outages:'Ажыратулар', alerts:'Шұғыл хабарламалар', complaints:'Шағымдар', voting:'Дауыс беру', payments:'Төлемдер', owner:'Менің нысандарым', logout:'Шығу',
    appName:'ТК Басқару', heroTitle:'Сіздің үйіңіз. Сіздің дауысыңыз.', heroText:'Тұрғындарға арналған бірыңғай портал — өтінімдер, жаңалықтар, дауыс беру және төлемдер бір жерде.', location:'Алматы · Қазақстан · 2026', login:'Жүйеге кіру', loginSubtitle:'Тұрғынның жеке кабинетіне кіріңіз', complex:'Тұрғын үй кешені', firstName:'Аты', lastName:'Тегі', password:'Құпия сөз', passwordPlaceholder:'Құпия сөзді енгізіңіз', signIn:'Кіру', noAccess:'Қолжетімділік жоқ па? Кешен басқарушысына хабарласыңыз.', nameError:'Аты-жөніңізді енгізіңіз', passwordError:'Құпия сөз кемінде 4 таңбадан тұруы керек', flatShort:'Пәт.', apartment:'Пәтер',
    emergencyNotification:'Шұғыл хабарлама', emergencyWaterText:'Бүгін сағат 09:00-ден 14:00-ге дейін жоспарлы жұмыстарға байланысты су өшіріледі.', moreDetails:'Толығырақ', homeTitle:'Басты бет', myRequests:'Менің өтінімдерім', activeCount:'белсенді', nextPayment:'Келесі төлем', paymentUntil:'10 қазанға дейін', openVotes:'Ашық дауыс берулер', waitingForVote:'сіздің дауысыңызды күтуде', outagesCount:'Ажыратулар', scheduled:'жоспарланған', latestNews:'Соңғы жаңалықтар', all:'Барлығы', newRequest:'Жаңа өтінім',
    maintenance:'Техникалық қызмет', general:'Жалпы', notice:'Хабарлама', community:'Қауымдастық', newsTitle:'Үй жаңалықтары', newsSubtitle:'Басқарушы компанияның ресми арнасы', allFilter:'Барлығы',
    news1Title:'Лифтке техникалық қызмет көрсету аяқталды', news1Body:'А кіреберісіндегі екі лифт те техникалық қызметтен өтіп, қалыпты жұмыс істеп тұр.', news2Title:'Басқарушы компаниямен жаңа келісімшарт жасалды', news2Body:'1 қазаннан бастап Almaty Comfort LLC коммуналдық қызметтер мен төлемдерді басқарады.', news3Title:'Тұрақ ережелері туралы еске салу', news3Body:'Апаттық шығуды бөгейтін көліктер үй ережелеріне сәйкес эвакуацияланады.', news4Title:'Сенбілік күзгі тазалық', news4Body:'5 қазанда аула тазалығы өтеді. Қолғап пен қаптар беріледі. Басталуы 10:00.',
    requestTitle:'Өтінім беру', requestSubtitle:'Үйдегі ақау немесе мәселе туралы хабарлаңыз', category:'Санат', chooseCategory:'Санатты таңдаңыз…', plumbing:'Сантехника', electrical:'Электрика', elevator:'Лифт', locksmith:'Құлып / Есік', cleaning:'Тазалық', heating:'Жылыту', roofing:'Шатыр', other:'Басқа', place:'Орын', placePlaceholder:'Мысалы, Б кіреберісі, 3-қабат', description:'Сипаттама', descriptionPlaceholder:'Мәселені толық сипаттаңыз…', similarRequest:'Ұқсас өтінім бар', similarText:'REQ-035: «Кіреберіс есігінің құлпы сынған» (11 дауыс). Осы өтінімге қосыласыз ба?', joinRecommended:'Қосылу (ұсынылады)', photoOptional:'Фото (міндетті емес)', photoAttached:'photo_20260929.jpg тіркелді', attachPhoto:'Фото тіркеу үшін басыңыз', sendRequest:'Өтінімді жіберу', requestSubmitted:'Өтінім жіберілді', requestRegistered:'REQ-042 өтінімі тіркелді', requestRegisteredText:'Басқарушы хабарлама алды. 24 сағат ішінде жауап күтіңіз.', submitAnother:'Тағы бір өтінім беру',
    requestsTitle:'Өтінімдер', requestsSubtitle:'Өтінімдеріңіздің тарихы мен мәртебесі', mine:'Менің өтінімдерім', allBuilding:'Үйдің барлық өтінімдері', join:'Қосылу', supported:'қолдады', accepted:'Қабылданды', inProgress:'Орындалуда', done:'Орындалды', pending:'Күтуде',
    req1:'Ас үй раковинасының астындағы ыстық су құбыры ағып тұр', req2:'4-қабат дәлізіндегі шам жыпылықтайды', req3:'Кіреберіс есігінің құлпы сынған — кілт тұрып қалады', req4:'3-қабаттағы қоқыс құбыры бітелген', req5:'6-қабат кіреберісіндегі терезе ілгегі сынған', req6:'Тұрақ маңындағы жертөле қабырғасында граффити бар', sanitation:'Санитария',
    outagesTitle:'Жоспарлы ажыратулар', outagesSubtitle:'Жоспарланған жұмыстар мен қызмет үзілістері', water:'Су', electricity:'Электр энергиясы', active:'Белсенді', upcoming:'Алдағы', allFloors:'Барлық қабаттар', floors15:'1–5 қабаттар', stairwellB:'Б кіреберісі', from:'Басталуы:', to:'Аяқталуы:', zone:'Аймақ:', reason1:'Құбырлар мен қысымды жоспарлы тексеру', reason2:'Жертөледегі электр қалқанын жаңарту', reason3:'Маусым алдында жылыту жүйесін шаю', reason4:'Жыл сайынғы қауіпсіздік тексеруі',
    alertsTitle:'Шұғыл хабарламалар', alertsSubtitle:'Басқарма мен апаттық қызметтердің маңызды хабарламалары', alert1Title:'Су өшірілді', alert1Body:'Ыстық және суық су 14:00-ге дейін өшірілді. Себебі: құбыр қысымын жоспарлы тексеру.', alert2Title:'Жертөледе түтін', alert2Body:'Өрт қызметі датчиктің жалған іске қосылуына келді. Қауіп жоқ.', alert3Title:'Жылыту маусымы', alert3Body:'1 қазаннан бастап жылыту маусымы басталады. Жүйелер уақытында іске қосылады.',
    complaintsTitle:'Көршілерге шағымдар', complaintsSubtitle:'Басқарушыға жасырын өтініш', fileComplaint:'Шағым беру', newComplaint:'Жаңа шағым', aboutFlat:'Кімге (пәтер)', subject:'Тақырып', subjectPlaceholder:'Шу, иіс, қоқыс…', details:'Толық мәлімет', anonymousInfo:'Шағымыңыз жасырын болады. Басқарушы екі тараппен де байланысады.', send:'Жіберу', complaintAccepted:'Шағым жасырын түрде қабылданды. Басқарушы оны 48 сағат ішінде қарайды.', history:'Өтініштер тарихы', underReview:'Қаралуда', resolved:'Шешілді', closed:'Жабылды', complaint1:'23:00-ден кейінгі шу', complaint2:'Ортақ дәліздегі темекі түтіні', complaint3:'Лифтте қарғыбаусыз ит', commonArea:'Ортақ аймақ',
    votingTitle:'Дауыс беру', votingSubtitle:'Шешімдер меншік иелерінің көпшілік дауысымен қабылданады', open:'Ашық', yes:'Қолдаймын', no:'Қарсымын', abstain:'Қалыс қалды', abstainAction:'Қалыс қалу', voted:'Дауыс берді', of:'ішінен', youVoted:'Сіз дауыс бердіңіз', vote1:'Барлық кіреберіске бейнебақылау камераларын орнату', vote2:'Ортақ аумақтарды аптасына 3 рет тазалау', vote3:'Үй қасбетін бояу — 2026 бюджет бабын бекіту', until:'дейін',
    paymentsTitle:'Төлемдер', paymentsSubtitle:'Коммуналдық жарналар', toPay:'Төлеуге', october:'Қазан 2026', paid2026:'2026 жылы төленді', nineMonths:'9 ай', debt:'Берешек', noOverdue:'Мерзімі өткен жоқ', paid:'Төленді', due:'Төлеуге', september:'Қыркүйек 2026', august:'Тамыз 2026', july:'Шілде 2026', communal:'Коммуналдық', repairFund:'Жөндеу қоры', security:'Күзет', total:'Барлығы', payOnline:'Онлайн төлеу',
    ownerTitle:'Менің нысандарым', ownerSubtitle:'Жалға берілген пәтерлерді басқару', tenant:'Жалға алушы', since:'Бастап', nextPaymentLabel:'Келесі төлем', activeRequests:'Белсенді өтінімдер', status:'Мәртебе', noDebt:'Берешек жоқ', overdue:'Мерзімі өтті', paymentMissing:'Төлем алынбады. Жалға алушыға хабарлама жіберілді.', sendReminder:'Еске салу жіберу'
  },
  en: {
    dashboard:'Home', news:'News', report:'Submit request', requests:'My requests', outages:'Outages', alerts:'Emergency', complaints:'Complaints', voting:'Voting', payments:'Payments', owner:'My properties', logout:'Log out',
    appName:'Residence Management', heroTitle:'Your home. Your voice.', heroText:'One portal for residents — requests, news, voting and payments in one place.', location:'Almaty · Kazakhstan · 2026', login:'Sign in', loginSubtitle:'Sign in to your resident account', complex:'Residential complex', firstName:'First name', lastName:'Last name', password:'Password', passwordPlaceholder:'Enter password', signIn:'Sign in', noAccess:'No access? Contact the complex manager.', nameError:'Enter your first and last name', passwordError:'Password must contain at least 4 characters', flatShort:'Apt.', apartment:'Apartment',
    emergencyNotification:'Emergency notification', emergencyWaterText:'Water outage today from 09:00 to 14:00 — scheduled maintenance.', moreDetails:'More details', homeTitle:'Home', myRequests:'My requests', activeCount:'active', nextPayment:'Next payment', paymentUntil:'due 10 Oct', openVotes:'Open votes', waitingForVote:'waiting for your vote', outagesCount:'Outages', scheduled:'scheduled', latestNews:'Latest news', all:'All', newRequest:'New request',
    maintenance:'Maintenance', general:'General', notice:'Notice', community:'Community', newsTitle:'Building news', newsSubtitle:'Official management company channel', allFilter:'All',
    news1Title:'Elevator maintenance completed', news1Body:'Both elevators in stairwell A have been serviced and are operating normally.', news2Title:'New management company contract signed', news2Body:'Starting 1 October, Almaty Comfort LLC will manage communal services and billing.', news3Title:'Parking rules reminder', news3Body:'Vehicles blocking the emergency exit will be towed according to building rules.', news4Title:'Autumn cleaning Saturday', news4Body:'Voluntary yard cleanup on 5 October. Gloves and bags are provided. Join us at 10:00.',
    requestTitle:'Submit request', requestSubtitle:'Report a fault or problem in the building', category:'Category', chooseCategory:'Choose a category…', plumbing:'Plumbing', electrical:'Electrical', elevator:'Elevator', locksmith:'Lock / Door', cleaning:'Cleaning', heating:'Heating', roofing:'Roofing', other:'Other', place:'Location', placePlaceholder:'e.g. Stairwell B, floor 3', description:'Description', descriptionPlaceholder:'Describe the problem in detail…', similarRequest:'A similar request already exists', similarText:'REQ-035: “Entrance door lock is broken” (11 votes). Join this request?', joinRecommended:'Join (recommended)', photoOptional:'Photo (optional)', photoAttached:'photo_20260929.jpg attached', attachPhoto:'Click to attach a photo', sendRequest:'Submit request', requestSubmitted:'Request submitted', requestRegistered:'Request REQ-042 registered', requestRegisteredText:'The manager has been notified. Expect a response within 24 hours.', submitAnother:'Submit another',
    requestsTitle:'Requests', requestsSubtitle:'History and status of your requests', mine:'My requests', allBuilding:'All building requests', join:'Join', supported:'supported', accepted:'Accepted', inProgress:'In Progress', done:'Done', pending:'Pending',
    req1:'Hot water pipe leaking under kitchen sink', req2:'Hallway light on 4th floor flickering', req3:'Entrance door lock broken — key jams', req4:'Rubbish chute blocked on floor 3', req5:'Broken window latch in stairwell floor 6', req6:'Graffiti on basement wall near parking', sanitation:'Sanitation',
    outagesTitle:'Scheduled outages', outagesSubtitle:'Scheduled work and service interruptions', water:'Water', electricity:'Electricity', active:'Active', upcoming:'Upcoming', allFloors:'All floors', floors15:'Floors 1–5', stairwellB:'Stairwell B', from:'From:', to:'To:', zone:'Zone:', reason1:'Scheduled pipe inspection and pressure testing', reason2:'Switchboard upgrade in basement', reason3:'Start-of-season heating system flush', reason4:'Annual safety certification inspection',
    alertsTitle:'Emergency notifications', alertsSubtitle:'Important messages from management and emergency services', alert1Title:'Water outage', alert1Body:'Hot and cold water are off until 14:00. Reason: scheduled pipe pressure inspection.', alert2Title:'Smoke in basement', alert2Body:'The fire service responded to a false sensor alarm in the basement. There is no danger.', alert3Title:'Heating season', alert3Body:'The heating season starts on 1 October. Systems are expected to start on time.',
    complaintsTitle:'Neighbour complaints', complaintsSubtitle:'Anonymous message to the manager', fileComplaint:'File complaint', newComplaint:'New complaint', aboutFlat:'About (apartment)', subject:'Subject', subjectPlaceholder:'Noise, smell, rubbish…', details:'Details', anonymousInfo:'Your complaint will be anonymous. The manager will contact both parties.', send:'Send', complaintAccepted:'Complaint accepted anonymously. The manager will review it within 48 hours.', history:'Request history', underReview:'Under review', resolved:'Resolved', closed:'Closed', complaint1:'Noise after 23:00', complaint2:'Cigarette smoke in shared hallway', complaint3:'Dog not on leash in elevator', commonArea:'Common area',
    votingTitle:'Voting', votingSubtitle:'Decisions are made by majority vote of property owners', open:'Open', yes:'Yes', no:'No', abstain:'Abstained', abstainAction:'Abstain', voted:'Voted', of:'of', youVoted:'You voted', vote1:'Install CCTV cameras in all stairwells', vote2:'Increase communal cleaning frequency to 3× per week', vote3:'Repaint building facade — approve 2026 budget item', until:'until',
    paymentsTitle:'Payments', paymentsSubtitle:'Communal contributions', toPay:'To pay', october:'October 2026', paid2026:'Paid in 2026', nineMonths:'9 months', debt:'Debt', noOverdue:'No overdue payments', paid:'Paid', due:'Due', september:'September 2026', august:'August 2026', july:'July 2026', communal:'Communal', repairFund:'Repair fund', security:'Security', total:'Total', payOnline:'Pay online',
    ownerTitle:'My properties', ownerSubtitle:'Manage rented apartments', tenant:'Tenant', since:'Since', nextPaymentLabel:'Next payment', activeRequests:'Active requests', status:'Status', noDebt:'No debt', overdue:'Overdue', paymentMissing:'Payment has not been received. The tenant was notified.', sendReminder:'Send reminder'
  }
} as const

export type Translation = { [K in keyof typeof translations.ru]: string }
